# --- Stage 1: Build ---
FROM node:24-alpine AS builder

WORKDIR /app

COPY ./package*.json .
RUN npm ci

COPY . .
RUN npm run build

# --- Stage 2: Runner ---
FROM node:24-alpine AS runner

WORKDIR /app

COPY package*.json .
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

CMD [ "node", "dist/index.js" ]
